"""SAMPLE validation harness for a scoring pipeline (synthetic data).
Usage: python3 harness.py [--report REPORT.md]   Exit 0 only if every blocking check passes."""
import datetime as dt, hashlib, json, math, random, sys

from momentum import contract, generate, score

AS_OF = generate.START + dt.timedelta(days=41)
results = []


def check(cid, name, ok, detail, blocking=True):
    results.append({"id": cid, "name": name, "ok": bool(ok), "detail": detail, "blocking": blocking})


def digest(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()[:16]


def golden_rows():
    rows = []
    for cid, prior, recent in (("g-up", 10, 20), ("g-flat", 10, 10), ("g-drop", 10, 0)):
        for d in range(14):
            day = AS_OF - dt.timedelta(days=13 - d)
            rows.append({"creator_id": cid, "date": day.isoformat(), "followers": 1000, "views": 100,
                         "engagements": prior if d < 7 else recent})
    return rows


def spearman(a, b):
    keys = [k for k in a if a[k] is not None and b.get(k) is not None]
    ra = {k: i for i, k in enumerate(sorted(keys, key=lambda k: a[k]))}
    rb = {k: i for i, k in enumerate(sorted(keys, key=lambda k: b[k]))}
    n = len(keys)
    return 1 - 6 * sum((ra[k] - rb[k]) ** 2 for k in keys) / (n * (n * n - 1))


def top(s, n=10):
    return [k for k, _ in sorted(((k, v) for k, v in s.items() if v is not None), key=lambda kv: (-kv[1], kv[0]))[:n]]


def run():
    clean = generate.clean_rows()
    dirty = generate.inject_defects(clean)

    # C1 contract
    good, q = contract.validate(clean, AS_OF)
    check("C1a", "Clean input passes the data contract", not q and len(good) == len(clean), f"{len(good)} rows, {len(q)} quarantined")
    good_d, q_d = contract.validate(dirty, AS_OF)
    reasons = sorted({x["reason"] for x in q_d})
    check("C1b", "Defective input is quarantined with reasons", len(q_d) >= 25 and "duplicate_key" in reasons and "negative_count" in reasons,
          f"{len(q_d)} of {len(dirty)} rows quarantined; reasons: {', '.join(reasons)}")

    for ver, fn in (("v1", score.score_v1), ("v2", score.score_v2)):
        s = fn(good, AS_OF)
        # C2 determinism and input-order independence
        shuffled = good[:]; random.Random(3).shuffle(shuffled)
        check(f"C2-{ver}", f"{ver}: same input, any row order, same output", digest(s) == digest(fn(good, AS_OF)) == digest(fn(shuffled, AS_OF)),
              f"output digest {digest(s)}")
        # C3 duplicates cannot change the score once the contract runs
        dup_good, _ = contract.validate(good + good[:50], AS_OF)
        check(f"C3-{ver}", f"{ver}: duplicated rows do not change scores", digest(fn(dup_good, AS_OF)) == digest(s), "50 duplicate rows added, then contract applied")
        # C4 monotonicity: more recent engagement never lowers a score
        viol = 0; tested = 0
        for cid in [k for k, v in s.items() if v is not None][:15]:
            bumped = [dict(r, engagements=r["engagements"] * 2) if r["creator_id"] == cid and
                      (AS_OF - dt.date.fromisoformat(r["date"])).days < 7 else r for r in good]
            tested += 1
            viol += fn(bumped, AS_OF)[cid] < s[cid]
        check(f"C4-{ver}", f"{ver}: doubling last-week engagement never lowers a score", viol == 0, f"{tested} creators tested, {viol} violations")
        # C5 bounds
        vals = [v for v in s.values() if v is not None]
        check(f"C5-{ver}", f"{ver}: scores finite and within 0-100", all(math.isfinite(v) and 0 <= v <= 100 for v in vals), f"min {min(vals):.2f}, max {max(vals):.2f}")
        # C6 cold start
        short = [k for k, v in s.items() if v is None]
        check(f"C6-{ver}", f"{ver}: creators with < {score.MIN_HISTORY_DAYS} days are not ranked", short == [f"creator-{i:03d}" for i in range(0, 40, 10)],
              f"unranked: {', '.join(short)}")
        if ver == "v1":
            s1 = s
        else:
            s2 = s

    # C7 golden fixtures (hand-computed for v1)
    g = score.score_v1(golden_rows(), AS_OF)
    want = {"g-up": round(100 / (1 + math.exp(-5)), 4), "g-flat": 50.0, "g-drop": round(100 / (1 + math.exp(5)), 4)}
    check("C7", "v1 matches hand-computed golden fixtures", g == want, json.dumps(g))

    # C8 version drift (advisory, not blocking): needs a named sign-off before v2 replaces v1
    overlap = len(set(top(s1)) & set(top(s2)))
    rho = spearman(s1, s2)
    check("C8", "v1 -> v2 drift within agreed tolerance (top-10 overlap >= 6)", overlap >= 6,
          f"top-10 overlap {overlap}/10, Spearman rho {rho:.2f}. Below tolerance means a ranking change customers will notice: product sign-off required.", blocking=False)
    return results


def report(rs):
    lines = ["# SAMPLE harness report (synthetic data)", "",
             f"As-of date: {AS_OF.isoformat()}. Generated by `python3 harness.py --report REPORT.md`.", "",
             "| Check | Result | Blocking | Detail |", "|---|---|---|---|"]
    for r in rs:
        lines.append(f"| {r['id']} {r['name']} | {'PASS' if r['ok'] else 'FAIL'} | {'yes' if r['blocking'] else 'advisory'} | {r['detail']} |")
    b = [r for r in rs if r["blocking"]]
    lines += ["", f"Blocking checks passed: {sum(r['ok'] for r in b)}/{len(b)}. Advisory checks failing: {sum(not r['ok'] for r in rs if not r['blocking'])}."]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    rs = run()
    text = report(rs)
    print(text)
    if "--report" in sys.argv:
        open(sys.argv[sys.argv.index("--report") + 1], "w").write(text)
    sys.exit(0 if all(r["ok"] for r in rs if r["blocking"]) else 1)
